### ISSUE TITLE
Password concern

### ISSUE THREAD

**Issue by Amir974** [pkozul/ha-floorplan-state-card#2]
I am a bit worried about adding the password in to the attributes which makes it clearly available in the state section of the dev tools...

is this mandatory for the implementation to work ?
is there a way to obscure / not show it ?

**Comment by pkozul** [comment]
The use of HTTPS should address your concern, but in any case, it's better to rely on Home Assistant use of password management rather than include it in the floorplan configuration. I have made this change, so that now, the password (if one is used) is taken from the web browser's local storage. This is where it is stored by Home Assistant's web application.

Resolved in 140c99d .
